CREATE DATABASE library;

\c library

CREATE TABLE AUTHORS(
    ID SERIAL PRIMARY KEY,
    FIRST_NAME TEXT,
    LAST_NAME TEXT
);

CREATE TABLE BOOKS(
    ID SERIAL PRIMARY KEY,
    TITLE TEXT,
    NO_OF_PAGES INT
);

CREATE TABLE AUTHOR_BOOKS(
    ID SERIAL PRIMARY KEY,
    AUTHOR_ID INT,
    BOOK_ID INT,
    CONSTRAINT fk_author FOREIGN KEY (AUTHOR_ID) REFERENCES AUTHORS(ID),
    CONSTRAINT fk_book FOREIGN KEY (BOOK_ID) REFERENCES BOOKS(ID)
);